# Generated by Django 5.0.6 on 2024-07-08 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("due_date", models.DateField()),
                ("total_survey", models.IntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            (0, "Not Yet"),
                            (1, "Started"),
                            (2, "Paused"),
                            (3, "Completed"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "allow_devices",
                    models.CharField(
                        choices=[
                            (1, "Mobile"),
                            (2, "Tablet"),
                            (3, "Laptop"),
                            (4, "Computer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("allow_countries", models.JSONField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started", models.IntegerField(default=0)),
                ("completed", models.IntegerField(default=0)),
                ("in_progress", models.IntegerField(default=0)),
                ("drop_off", models.IntegerField(default=0)),
                ("screen_out", models.IntegerField(default=0)),
                ("rotten", models.IntegerField(default=0)),
                ("disqualified", models.IntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.projects",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSurveyStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_unique_identification", models.CharField(max_length=100)),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            (0, "Disqualified"),
                            (1, "Started"),
                            (2, "Completed"),
                            (3, "In Progress"),
                            (4, "Drop Off"),
                            (5, "Screen Out"),
                            (6, "Rotten"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.projects",
                    ),
                ),
            ],
        ),
    ]
